### ISSUE TITLE
[Bug]: Update license and credits

### ISSUE THREAD

**Issue by nickvidal** [enarx/cryptle#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

We have Apache and MIT licenses.

Credits:
- Rust HTTP Server: Harald
  - Single Player: Richard
  - Multi Player: Nick
- Client: Nick (current) and Vanessa Stewart (original author)

### Expected Behaviour

Have one unique license (Apache 2.0)

### Environment Information

-

**Comment by aryankaushikdev** [comment]
This issue has been resolved under Pull Request #6
