### ISSUE TITLE
[Feature]: Lighthouse improvements

### ISSUE THREAD

**Issue by nickvidal** [enarx/cryptle#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- [x] Performance
- [ ] Accessibility
  - [ ] Buttons do not have an accessible name (help, stats)
  - [ ] Form elements do not have associated labels (input#multiCheckbox)
- [x] Best practices
- [ ] SEO
  - [ ] Document does not have a meta description

**Comment by MikeCamel** [comment]
What's "Lighthouse" in this context, please?

**Comment by nickvidal** [comment]
It's a tool by Google that analyses your web application and recommends various improvements.

**Comment by aryankaushikdev** [comment]
The following issues have been resolved:

1.  Accessibility - (Completed)
     Buttons do not have an accessible name (help, stats)
     Form elements do not have associated labels (input#multiCheckbox)

2. SEO- (Completed)
    Document does not have a meta description
